#!/usr/bin/env ruby

require 'bundler/setup' unless defined?(Bundler)
require 'octokit'
require 'pry'
require 'yaml'

lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'zodiac/service/fetcher'
require 'zodiac/service/github'
require 'zodiac/service/github/activity_feed'

Zodiac::Service::GitHub.new.pry
